### ISSUE TITLE
Add extra lex file suffixes equivalent to the yacc suffixes  

### ISSUE THREAD

**Issue by willwray** [faustinoaq/vscode-lex-flex-yacc-bison#4]
The extension currently recognises lex / flex suffixes ".l" and ".flex"
while for yacc / bison it recognises ".y", ".yy", ".ypp", ".yxx", ".y++" and ".bison" / ".BISON"

Consider extending the set of lex suffixes recognised similarly:
```
.l, .ll, .l++, .lxx, and .lpp
```
See, for example, [autotools](https://www.gnu.org/software/automake/manual/html_node/Yacc-and-Lex.html) yacc & lex docs:

> Similarly, lex source files can be used to generate C or C++; the extensions .l, .ll, .l++, .lxx, and .lpp are recognized.

Workaround: change language mode to flex / lex:
Ctrl-Shift-P -> "Change Language Mode" -> Flex/lex

**Comment by willwray** [comment]
Ah - I see there's already a PR for exactly this #2
(with the same link too).

**Comment by faustinoaq** [comment]
@willwray Thank you for opening this issue, I just merged the PR, Sorry for late response, I'll publish a new version soon :+1:

**Comment by GitMensch** [comment]
this should be closed as fixed

**Comment by willwray** [comment]
Fixed

**Comment by GitMensch** [comment]
@willwray as the author you may click on "close issue" ;-)

**Comment by willwray** [comment]
Ha, thanks; I'd hit the wrong button
